name: Publish

on:
   pull_request:
     branches:
       - main
   push:
     branches:
       - main

jobs:

  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: 🔨 Setup .NET 6.X SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'
        

    - name: 🔨 Setup .NET 7.X SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'


    - name: Release Dll
      run : dotnet build -c Release
    
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/XCodeless.DI/XCodeless.DI.csproj
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/XCodeless.DI/XCodeless.DI.Ext.Runtime.csproj
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}