name: XCodeless.DI unit test

on:
   pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - test

jobs:

    linux:
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
          
      - name: 🚦 Test
        run: dotnet test './test/ut/Runtime.Test' -c Release
     
    windows:
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      runs-on: windows-latest  
      steps:

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'    

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: 🚦 Test
        run: dotnet test "./test/ut/Runtime.Test" -c Release
   
    mac:
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      runs-on: macos-latest
            
      steps:

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'
          
      - name: 🚦 Test
        run: dotnet test './test/ut/Runtime.Test' -c Release
